variable "RG-name" {}
variable "RG-location" {}
variable "tag" {}
variable "VNET-name" {}
variable "VNET-ip" {}
variable "sub-name" {}
variable "sub-ip" {}
variable "CGD-LB-name" {}
variable "backend-add-name" {}
variable "backend-ip-add" {}
variable "Public_ip_name" {}
variable "Static_NIC_name" {}
variable "private_ip_add" {}
variable "vm_name" {}
variable "vm_size" {}
variable "os_name" {}
variable "os_disk_size" {}
variable "computer_name" {}
variable "user_name" {}
variable "user_password" {}
variable "managed-disk-name" {}
variable "managed_disk_size" {}
variable "coun" {}
variable "NSG-name" {}
variable "security_rule_name" {}
variable "security_rule_priority" {}
variable "security_rule_direction" {}
variable "security_rule_access" {}
variable "security_rule_protocol" {}
variable "security_rule_source_port_range" {}
variable "security_rule_destination_port_range" {}
variable "security_rule_source_address_prefix" {}
variable "security_rule_destination_address_prefix" {}
variable "host-pool-name" {}
variable "host-pool-type" {}
variable "personal_desktop_assignment_type" {}
variable "hp-LB-type" {}
variable "desktopapp-name" {}
variable "workspace-name" {}
